beauty/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()


urlpatterns = patterns('',

    # Django Admin (unused so far.)
    (r'^admin/', include(admin.site.urls)),

    url(r'^signup/?', 'uui.views.signup', name='signup'),

    # User-facing site, 'uui' app.
    url(r'^$', 'uui.views.search', name='search'),
    url(r'^results/', 'uui.views.results', name='results'),
    url(r'^res/', 'uui.views.ajax_results', name='ares'),
    url(r'^booking/', 'uui.views.booking', name='booking'),
    url(r'^confirmation/', 'uui.views.confirmation', name='confirmation'),
    url(r'^logout/',
        'django.contrib.auth.views.logout',
        {'next_page': '/'},
        name='logout'),

    url(r'^login/',
        'django.contrib.auth.views.login',
        {'template_name': 'login.html'},
        name='login'),

    # Spa-facing site.
    url(r'^spa/', include('spasui.urls')),

    # Rep's support site, apps.
    url(r'^repui/?$', 'repui.views.index', name='repui'),

    # Semantic REST API.
    url(r'^ref/', include('semui.urls')),

    # Static media (should be served directly by the web server in production.)
    (
        r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT},
        ),

    )

beauty/spasui/forms.py
from django import forms


class SpaInfoForm(forms.Form):
    spa_name = forms.CharField(max_length=100)
    address = forms.CharField(max_length=100)
    city = forms.ChoiceField(
        choices=[('SanFrancisco', 'San Francisco')]
        )
    neighborhood = forms.ChoiceField(
        choices=[
            ('', '---'),
            ('Richmond_Presidio', 'Richmond/Presidio'),
            ('Marina_Cow_Hollow', 'Marina/Cow Hollow'),
            ('Pacific_Heights', 'Pacific Heights'),
            ('Russian_Hill_Nob_Hill', 'Russian Hill/Nob Hill'),
            ('North_Beach_Fishermans_Wharf', "North Beach/Fisherman's Wharf"),
            ('Union_Sq_Civic_Ctr_FiDi', 'Union Sq/Civic Ctr/FiDi'),
            ('SoMa_South_Beach', 'SoMa/South Beach'),
            ('Western_Addition', 'Western Addition'),
            ('Haight', 'Haight'),
            ('Castro', 'Castro'),
            ('Mission', 'Mission'),
            ('Potrero_Hill', 'Potrero Hill'),
            ('Noe_Valley', 'Noe Valley'),
            ('Bernal_Heights', 'Bernal Heights'),
            ('Twin_Peaks', 'Twin Peaks'),
            ('Sunset_Lake_Merced', 'Sunset/Lake Merced'),
            ('Ingleside_Excelsior', 'Ingleside/Excelsior'),
            ]
        )
    hours = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=100)
    website = forms.URLField(max_length=100)
    email_contact = forms.EmailField()
    pictures = forms.CharField(max_length=100)
    description = forms.CharField(max_length=100)
    cancel_policy = forms.CharField(
        max_length=2000,
        label="Cancellation Policy",
        widget=forms.Textarea,
        )

beauty/templates/booking.html
{% extends "base.html" %}


{% block html_head %}
<style>
	@import url(http://fonts.googleapis.com/css?family=Pacifico|Chewy|Dancing+Script:400,700);

	html {
		font-size: 62.5%;
	}

	body {
		background-color: #eee;
	}

	#header h1 {
		font-family: Pacifico; 
		font-size: 42px;
		font-size: 4.2rem;	
		color: #7FBA02;
		margin: 10px 0 20px 0;
	    text-align: center;
	}

	#header h1 a {
		color: #7FBA02;
	}
	
	#header h1 a:hover {
		color: #5f8b01;
	}

	#content {
	    background-color: #FFFFFF;
	    border: 1px solid #E2E2E2;
	    box-shadow: 0 2px 2px #DDDDDD;
	    color: #666666;
	    padding-right: 0px;
	    padding-bottom: 40px;
		position: relative;		
	}
	
	.booking_photos {
		padding: 8px;
		background: #eee;
		border: 1px solid #fff;
		box-shadow: 0px 2px 10px #333;
		-moz-box-shadow: 0px 2px 10px #333;
		-webkit-box-shadow: 0px 2px 10px #333;
		position: relative;
		margin: 0 0 0 25px;
		/*
		-webkit-transform: rotate(-1.5deg);
		-moz-transform: rotate(-1.5deg);
		*/
	}
	
	.sosumi {
		font-size:10px; 
		color: #aaa;
	}
	
</style>
{% endblock %}


{% block title %}
Book - SpaStalker
{% endblock %}


{% block body %}
<div class="container">

	<!-- HEADER -->
	<div id="header" class="row">
		<div class="twelve columns">
			<h1><a href="/">SpaStalker</a></h1>
		</div>
	</div>

	<!-- CONTENT -->
	<div id="content" class="row">
    	<div class="twelve columns">
			<div class="one columns"></div>
			<div class="ten columns"><br><br>
			<p><img src="/static/fakedata/DMB/interior02.jpg" class="booking_photos" width="300" align="right">
		
				<h2 style="color: #027FB9;">Swedish Massage - $100</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce fringilla sem sed nibh venenatis placerat. Mauris eu nulla eu tellus pulvinar aliquet in ac metus. Proin scelerisque pellentesque eros, nec porta purus convallis in. Sed pellentesque tempor neque id imperdiet. Phasellus cursus lacinia augue eu eleifend.</p>

				<center><a href="/confirmation" class="large nice round red button">Yeah, book it!</a></center><br><br>
		
				<hr>
				
				<p class="sosumi">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce fringilla sem sed nibh venenatis placerat. Mauris eu nulla eu tellus pulvinar aliquet in ac metus. Proin scelerisque pellentesque eros, nec porta purus convallis in. Sed pellentesque tempor neque id imperdiet. Phasellus cursus lacinia augue eu eleifend. Vestibulum vitae sapien vel leo ornare ultrices. Vivamus id tortor tortor. Vestibulum tempus, libero at pretium euismod, turpis velit mollis erat, vitae suscipit sapien neque vitae mi.</p>
				</div>
			<div class="one columns"></div>
    	</div>
	</div>

	<!-- FOOTER -->
	<div class="row">
		<div class="twelve columns"><br><br>

		</div>
	</div>

</div><!-- container -->
{% endblock %}

beauty/templates/calendar.html
{% extends "base.html" %}
{% block title %}Spa Calendar{% endblock %}
{% block html_head %}
<link rel="stylesheet" href="/static/calendar.css" type="text/css">
<link href='http://fonts.googleapis.com/css?family=Pacifico|Chewy|Dancing+Script:400,700' rel='stylesheet' type='text/css'>
<script type="text/javascript">

$(function(){

        function build_trenches() {
{% for trench, treats in trenches %}
            var trenche = $("#trench_{{ trench }}_div");
    {% for treatment in treats %}
            trenche.append("{{ treatment }}<br>");
{% endfor %}{% endfor %}
        }

        build_trenches();

    $( "#from_date_cal" ).datepicker({
        minDate: "+0D",
        showOtherMonths: true,
        selectOtherMonths: true,
        altField: '#from_date'
    });

    $( "#to_date_cal" ).datepicker({
        minDate: "+0D",
        showOtherMonths: true,
        selectOtherMonths: true,
        altField: '#to_date'
    });

});

</script>
{% endblock %}
{% block body %}
<img id="background" src="/static/bg/537183095_9b2abcba55_b.jpg">
<div class="container">

<div class="row"><div class="twelve columns">
  <h1 class="arch">SpaStalkers</h1>
  <h2>spa_name</h2>
</div></div>

<form method="POST" action="#" class="nice">{% csrf_token %}

<div class="row"><div class="twelve columns centered">
<div id="location" class="main">
	<h1>Where</h1>
    <ul class="block-grid mobile four-up">
    {% for loc in locations %}
        <li>
            <label for="{{ loc.label }}">
                <input name="{{ loc.label }}" id="{{ loc.label }}" type="checkbox" />
                {{ loc.name }}
            </label>
        </li>
    {% endfor %}
    </ul>
    Wants pawn term, dare worsted ladle gull hoe lift wetter murder inner
    ladle cordage, honor itch offer lodge dock florist. Disk ladle gull
    orphan worry ladle cluck wetter putty ladle rat hut, an fur disk
    raisin pimple colder Ladle Rat Rotten Hut.
</div>
</div></div>

<div class="row"><div class="twelve columns centered">
<div id="treatments" class="main">
	<h1>What</h1>
    <ul id="trenches" class="block-grid mobile three-up">
      {% for trench, treats in trenches %}
        <li>
              <label for="trench_{{ trench }}">
                <input name="trench_{{ trench }}" id="trench_{{ trench }}" type="checkbox" />
                {{ trench }}<br>
                <div id="trench_{{ trench }}_div" class="trenche_list"></div>
              </label>
        </li>
      {% endfor %}
    </ul>
    Wan moaning, Rat Rotten Hut's murder colder inset, "Ladle Rat Rotten
    Hut, heresy ladle basking winsome burden barter an shirker cockles.
    Tick disk ladle basking tutor cordage offer groin-murder hoe lifts
    honor udder site offer florist. Shaker lake! Dun stopper laundry
    wrote! An yonder nor sorghum-stenches, dun stopper torque wet
    strainers!"
</div>
</div></div>

<div class="row"><div class="twelve columns centered">
<div id="time" class="main">
	<h1>When</h1>

	<div class="row">
	  <div class="six columns">
	    <h3>Date From:</h3>
        <div id="from_date_cal"></div>
        <input name="from_date" id="from_date" type="hidden" />
      </div>
	  <div class="six columns">
	    <h3>Date To:</h3>
        <div id="to_date_cal"></div>
        <input name="to_date" id="to_date" type="hidden" />
      </div>
    </div>

    "Hoe-cake, murder," resplendent Ladle Rat Rotten Hut, an tickle ladle
    basking an stuttered oft. Honor wrote tutor cordage offer
    groin-murder, Ladle Rat Rotten Hut mitten anomalous woof. "Wail,
    wail, wail!" set disk wicket woof, "Evanescent Ladle Rat Rotten Hut!
    Wares are putty ladle gull goring wizard ladle basking?"

	<div class="row">
	  <div class="six columns">
	    <h3>Time From:</h3>
<select name="from_time">
<option value="05:00" selected="selected">5:00 AM</option>
<option value="05:15">5:15 AM</option>
<option value="05:30">5:30 AM</option>
<option value="05:45">5:45 AM</option>
<option value="06:00">6:00 AM</option>
<option value="06:15">6:15 AM</option>
<option value="06:30">6:30 AM</option>
<option value="06:45">6:45 AM</option>
<option value="07:00">7:00 AM</option>
<option value="07:15">7:15 AM</option>
<option value="07:30">7:30 AM</option>
<option value="07:45">7:45 AM</option>
<option value="08:00">8:00 AM</option>
<option value="08:15">8:15 AM</option>
<option value="08:30">8:30 AM</option>
<option value="08:45">8:45 AM</option>
<option value="09:00">9:00 AM</option>
<option value="09:15">9:15 AM</option>
<option value="09:30">9:30 AM</option>
<option value="09:45">9:45 AM</option>
<option value="10:00">10:00 AM</option>
<option value="10:15">10:15 AM</option>
<option value="10:30">10:30 AM</option>
<option value="10:45">10:45 AM</option>
<option value="11:00">11:00 AM</option>
<option value="11:15">11:15 AM</option>
<option value="11:30">11:30 AM</option>
<option value="11:45">11:45 AM</option>
<option value="12:00">12:00 PM</option>
<option value="12:15">12:15 PM</option>
<option value="12:30">12:30 PM</option>
<option value="12:45">12:45 PM</option>
<option value="13:00">1:00 PM</option>
<option value="13:15">1:15 PM</option>
<option value="13:30">1:30 PM</option>
<option value="13:45">1:45 PM</option>
<option value="14:00">2:00 PM</option>
<option value="14:15">2:15 PM</option>
<option value="14:30">2:30 PM</option>
<option value="14:45">2:45 PM</option>
<option value="15:00">3:00 PM</option>
<option value="15:15">3:15 PM</option>
<option value="15:30">3:30 PM</option>
<option value="15:45">3:45 PM</option>
<option value="16:00">4:00 PM</option>
<option value="16:15">4:15 PM</option>
<option value="16:30">4:30 PM</option>
<option value="16:45">4:45 PM</option>
<option value="17:00">5:00 PM</option>
<option value="17:15">5:15 PM</option>
<option value="17:30">5:30 PM</option>
<option value="17:45">5:45 PM</option>
<option value="18:00">6:00 PM</option>
<option value="18:15">6:15 PM</option>
<option value="18:30">6:30 PM</option>
<option value="18:45">6:45 PM</option>
<option value="19:00">7:00 PM</option>
<option value="19:15">7:15 PM</option>
<option value="19:30">7:30 PM</option>
<option value="19:45">7:45 PM</option>
<option value="20:00">8:00 PM</option>
<option value="20:15">8:15 PM</option>
<option value="20:30">8:30 PM</option>
<option value="20:45">8:45 PM</option>
<option value="21:00">9:00 PM</option>
</select>
      </div>
	  <div class="six columns">
	    <h3>Time To:</h3>
<select name="to_time">
<option value="05:00">5:00 AM</option>
<option value="05:15">5:15 AM</option>
<option value="05:30">5:30 AM</option>
<option value="05:45">5:45 AM</option>
<option value="06:00">6:00 AM</option>
<option value="06:15">6:15 AM</option>
<option value="06:30">6:30 AM</option>
<option value="06:45">6:45 AM</option>
<option value="07:00">7:00 AM</option>
<option value="07:15">7:15 AM</option>
<option value="07:30">7:30 AM</option>
<option value="07:45">7:45 AM</option>
<option value="08:00">8:00 AM</option>
<option value="08:15">8:15 AM</option>
<option value="08:30">8:30 AM</option>
<option value="08:45">8:45 AM</option>
<option value="09:00">9:00 AM</option>
<option value="09:15">9:15 AM</option>
<option value="09:30">9:30 AM</option>
<option value="09:45">9:45 AM</option>
<option value="10:00">10:00 AM</option>
<option value="10:15">10:15 AM</option>
<option value="10:30">10:30 AM</option>
<option value="10:45">10:45 AM</option>
<option value="11:00">11:00 AM</option>
<option value="11:15">11:15 AM</option>
<option value="11:30">11:30 AM</option>
<option value="11:45">11:45 AM</option>
<option value="12:00">12:00 PM</option>
<option value="12:15">12:15 PM</option>
<option value="12:30">12:30 PM</option>
<option value="12:45">12:45 PM</option>
<option value="13:00">1:00 PM</option>
<option value="13:15">1:15 PM</option>
<option value="13:30">1:30 PM</option>
<option value="13:45">1:45 PM</option>
<option value="14:00">2:00 PM</option>
<option value="14:15">2:15 PM</option>
<option value="14:30">2:30 PM</option>
<option value="14:45">2:45 PM</option>
<option value="15:00">3:00 PM</option>
<option value="15:15">3:15 PM</option>
<option value="15:30">3:30 PM</option>
<option value="15:45">3:45 PM</option>
<option value="16:00">4:00 PM</option>
<option value="16:15">4:15 PM</option>
<option value="16:30">4:30 PM</option>
<option value="16:45">4:45 PM</option>
<option value="17:00">5:00 PM</option>
<option value="17:15">5:15 PM</option>
<option value="17:30">5:30 PM</option>
<option value="17:45">5:45 PM</option>
<option value="18:00" selected="selected">6:00 PM</option>
<option value="18:15">6:15 PM</option>
<option value="18:30">6:30 PM</option>
<option value="18:45">6:45 PM</option>
<option value="19:00">7:00 PM</option>
<option value="19:15">7:15 PM</option>
<option value="19:30">7:30 PM</option>
<option value="19:45">7:45 PM</option>
<option value="20:00">8:00 PM</option>
<option value="20:15">8:15 PM</option>
<option value="20:30">8:30 PM</option>
<option value="20:45">8:45 PM</option>
<option value="21:00">9:00 PM</option>
</select>
      </div>
    </div>

<input type="submit" id="mark_available" value="Mark Available" class="nice round small blue button">
</div>
</div></div>

</form>

</div><!-- container -->
{% endblock %}

beauty/templates/dashboard.html
{% extends "base.html" %}
{% block html_head %}
<script type="text/javascript" src="/static/js/libby.js"></script>
<script type="text/javascript" src="/static/js/bbone/underscore.js"></script>
<script type="text/javascript" src="/static/js/bbone/backbone.js"></script>
<link type="text/css" href="/static/dashboard.less" rel="stylesheet/less">
<script type="text/javascript" src="/static/js/less.js"></script>
<script type="text/javascript" src="/static/js/jquery.tmpl.js"></script>
<script type="text/javascript" src="/static/js/knockout-1.2.1.debug.js"></script>
<script type="text/javascript" src="/static/js/d3/d3.js"></script>
<script type="text/javascript" src="/static/js/d3/d3.layout.js"></script>
<style>
	@import url(http://fonts.googleapis.com/css?family=Pacifico|Chewy|Dancing+Script:400,700);
	@import url(http://fonts.googleapis.com/css?family=Josefin+Sans:400,100|Istok+Web|Philosopher);
</style>

{# StaffMember pane_4 Step "Dashboard" ================================================= #}
<script id="tile_template" type="text/x-jquery-tmpl">
<div class="tile">
    <a href="#" data-bind="text:name, click: make_current"></a>
    <span data-bind="visible: extraCost">[!]</span>
    <br>
    <span class="clip" data-bind="text:description"></span>
    <a href="#" class="clip" data-bind="click: remove">Remove</a>
</div>
</script>

{# Treatments Outline Display Steps 2 & 3 ================================================= #}
<script id="proc_template" type="text/x-jquery-tmpl">
<div class="proc" data-bind="visible:supported">
    <span data-bind="text:name, click:make_current, style: { 'paddingLeft': '1.75em' }"></span>
</div>
</script>

<script id="proc_category_template" type="text/x-jquery-tmpl">
<div class="proc_display">
    <span data-bind="text:name"></span>
    <p data-bind="template: {name:'proc_template', foreach: children}"></p>
</div>
</script>

{# Accordion Display Step 2 ================================================= #}
<script id="accordion_proc_template" type="text/x-jquery-tmpl">
<input class="tile" type="checkbox" data-bind="event: {change:toggle}, attr: { id: 'check_' + name, name: 'check_' + name }"/>
<label data-bind="attr: { for: 'check_' + name }, text:name"></label>
<br>
</script>

<script id="accordion_proc_category_template" type="text/x-jquery-tmpl">
<h3><a href="#" data-bind="text:name"></a></h3>
<div data-bind="template: {name:'accordion_proc_template', foreach: children}"></div>
</script>

{# Full Treatment Menu Step 4 ================================================= #}
<script id="review_proc_template" type="text/x-jquery-tmpl">
<div class="review_proc" data-bind="visible:supported">
    <h4 data-bind="text:name"></h4>
    <span data-bind="text:nickname"></span>
    <span data-bind="text:formatted_price"></span>
    <span data-bind="text:duration"></span>
</div>
</script>

<script id="review_proc_category_template" type="text/x-jquery-tmpl">
<div class="review_proc_category">
    <div class="review_procs" data-bind="template: {name:'review_proc_template', foreach: children}"></p>
    </div>
</div>
</script>

<script type="text/javascript">
//-------------------------------------------------------
// Static Data
//

var root = {{ tree_data|safe }};

</script>
<script type="text/javascript" src="/static/js/lib/dashboard.js"></script>

{% endblock %}
{% block title %}Dashboard - SpaStalker{% endblock %}
{% block body %}
<div class="container">

  <div class="row"><div class="twelve columns">
    <h1 id="logotype"><a href="/">SpaStalker</a></h1>
  </div></div>{# columns row #}

  <div class="row"><div class="twelve columns">
    <div id="crumbs">
    <h3>
    <a id="0_link" href="#step/0">Step 1</a> &mdash; &gt;
    <a id="1_link" href="#step/1">Step 2</a> &mdash; &gt;
    <a id="2_link" href="#step/2">Step 3</a> &mdash; &gt;
    <a id="3_link" href="#step/3">Step 4</a> &mdash; &gt;
    <a id="dash_link" href="#d">Dashboard</a>
    </h3>
    </div>
  </div></div>{# columns row #}

<div class="row"><div class="twelve columns">
<div id="hull">


<div id="pane_0" class="pane">
<div class="row">
  <div class="twelve columns">
  <div class="panel">
    <h2>Basic Information</h2>
    <form class="nice">
    <table>
    <tr><th><label for="id_spa_name">Spa name:</label></th><td><input id="id_spa_name" type="text" name="spa_name" class="input-text" maxlength="100" /></td></tr>
    <tr><th><label for="id_address">Address:</label></th><td><input id="id_address" type="text" name="address" class="input-text" maxlength="100" /></td></tr>
    <tr><th><label for="id_neighborhood">Neighborhood:</label></th><td><input id="id_neighborhood" type="text" name="neighborhood" class="input-text" maxlength="100" /></td></tr>
    <tr><th><label for="id_hours">Hours:</label></th><td><input id="id_hours" type="text" name="hours" class="input-text" maxlength="100" /></td></tr>
    <tr><th><label for="id_phone">Phone:</label></th><td><input id="id_phone" type="text" name="phone" class="input-text" maxlength="100" /></td></tr>

    <tr><th><label for="id_website">Website:</label></th><td><input id="id_website" type="text" name="website" class="input-text" maxlength="100" /></td></tr>
    <tr><th><label for="id_email_contact">Email contact:</label></th><td><input type="text" name="email_contact" id="id_email_contact" class="input-text" /></td></tr>
    <tr><th><label for="id_pictures">Pictures:</label></th><td><input id="id_pictures" type="text" name="pictures" class="input-text" maxlength="100" /></td></tr>
    <tr><th><label for="id_description">Description:</label></th><td><input id="id_description" type="text" name="description" class="input-text" maxlength="100" /></td></tr>
    <tr><th><label for="id_wheelchair_accessible">Wheelchair accessible:</label></th><td><input type="checkbox" name="wheelchair_accessible" id="id_wheelchair_accessible" /></td></tr>
    <tr><th><label for="id_espanol">Espanol:</label></th><td><input type="checkbox" name="espanol" id="id_espanol" /></td></tr>
    </table>
    </form>
    <div class="button_bar_bottom"><a class="blueman button radius" href="#step/1">Next &gt;</a></div>
  </div>{# panel #}
  </div>{# columns  #}
</div>{# row #}
</div>{# pane_0 #}


<div id="pane_1" class="pane">
<div class="row">
  <div class="twelve columns">
  <div class="panel">
    <h2>Services Provided</h2>
    <div class="row">
    <div class="seven columns">

        <form>
	    <div id="choose" class="roundy main_panel" data-bind="template: {name:'accordion_proc_category_template', foreach: obj_treatments}">
	    </div>{# "choose" DIV #}
        </form>

    </div>{# columns #}

    <div class="five columns">
    <div class="magic">
      <h4>Wants pawn term, </h4>
      <p>
        ..dare worsted ladle gull hoe lift wetter murder inner
        ladle cordage, honor itch offer lodge dock florist. Disk ladle gull
        orphan worry ladle cluck wetter putty ladle rat hut, an fur disk
        raisin pimple colder Ladle Rat Rotten Hut.
      </p>
      <p data-bind="template: {name:'proc_category_template', foreach: obj_treatments}"></p>
    </div>{#  magic #}
    </div>{# columns #}

    </div>{# row #}

    <div class="button_bar_bottom" style="margin-top:18px"><a class="blueman button radius" href="#step/2">Next &gt;</a></div>

  </div>{# panel #}
  </div>{# columns  #}
</div>{# row #}
</div>{# pane_1 #}


<div id="pane_2" class="pane">
<div class="row">
  <div class="twelve columns">
  <div class="panel">
    <h2>Customize Menu</h2>

    <div class="row">

    <div class="three columns">
      <p data-bind="template: {name:'proc_category_template', foreach: obj_treatments}"></p>
    </div>{# columns #}

    <div class="nine columns">
    <div class="proc_detail">
        <h3 data-bind="text: current_proc().name"></h3>
        <h5>Details</h5>
            <div class="sub_proc" data-bind="visible:current_proc().supported">
                <span data-bind="text:current_proc().nickname"></span>
                <span data-bind="text:current_proc().formatted_price"></span>
                <span data-bind="text:current_proc().duration"></span>
            </div>
            <form class="nice">
                <input class="input-text" type="text" data-bind="value:current_proc().nickname" placeholder="None Selected"><br>
                <input class="input-text" type="text" data-bind="value:current_proc().price" placeholder="Price"><br>
                <input class="input-text" type="text" data-bind="value:current_proc().duration" placeholder="Duration"><br>
                <button id="add_proc">Add</button>
                <button id="del_proc">Delete</button>
            </form>

    </div>
    </div>{# columns #}

    </div>{# row #}

    <div class="button_bar_bottom"><a class="blueman button radius" href="#step/3">Next &gt;</a></div>
  </div>{# panel #}
  </div>{# columns  #}
</div>{# row #}
</div>{# pane_2 #}


<div id="pane_3" class="pane">
<div class="row">
  <div class="twelve columns">
  <div class="panel">
    <h2>Spa Menu Review</h2>
    <div data-bind="template: {name:'review_proc_category_template', foreach: obj_treatments}"></div>
    <div class="button_bar_bottom"><a class="blueman button radius" href="#d">Next &gt;</a></div>
  </div>{# panel #}
  </div>{# columns  #}
</div>{# row #}
</div>{# pane_3 #}


<div id="pane_4" class="pane">
<div class="row">
  <div class="twelve columns">
  <div class="panel">
  <div class="row">

  <div class="four columns"><div id="hoo">
    <h2>Staff</h2>
    <p data-bind="template: {name:'tile_template', foreach: stuffs}"></p>
    <form class="nice">
      <button id="add_staff" data-bind="click: add_staff_member">Add Staff Member</button>
      <input id="staff_name" name="staff_name" class="input-text small" type="text" placeholder="Add Staff Member">
    </form>
  </div>{# hoo #}</div>

  <div class="eight columns"><div id="boy">
    <div class="row"><div class="twelve columns">
      <div id="aa" class="cake">
        <h3>Procedures for <span data-bind="text: current().name"></span></h3>
        <div id="chart"></div>
      </div>{# panel #}
    </div></div>{# columns row #}
  </div>{# boy #}</div>

  </div>{# row #}
  </div>{# panel #}
  </div>{# columns  #}
</div>{# row #}
</div>{# pane_4 #}


</div>{# hull #}
</div></div>{# columns row #}

</div>{# container #}
{% endblock %}