juvume/look/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('',
    url(r'^$', 'look.views.home', name='booking_home'),
    url(r'^inv$', 'look.views.inv', name='inv'),
    url(r'^book$', 'look.views.book', name='book'),
    url(r'^book_info$', 'look.views.book_info', name='book_info'),
    url(r'^book_confirm$', 'look.views.book_confirm', name='book_confirm'),
    url(r'^book_congrats$', 'look.views.book_congrats', name='book_congrats'),
    url(r'^hooray$', 'look.views.hooray', name = 'hooray'),
    )

juvume/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic.simple import direct_to_template


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', direct_to_template, {'template': 'index.html'}),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # User-facing site.
    url(r'^look/', include('look.urls')),
    )

# Static media (served directly by the web server in production.)
if not settings.PRODUCTION:
    urlpatterns += patterns('',
        (
            r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT},
            ),
        )

juvume/look/models.py
from django.db import models

# Create your models here.

class Spa(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    appt_color = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name', )

class Category(models.Model):
    DECISION_TREE = (
            ('Therapeutic', 'Therapeutic'),
            ('Thai', 'Thai'),
            ('Hot Stone', 'Hot Stone'),
            ('Reflexology', 'Reflexology'),
            ('Facials', 'Facials'),
            ('Lash Extensions', 'Lash Extensions'),
            ('Lash Tinting', 'Lash Tinting'),
            ('Brow Tinting', 'Brow Tinting'),
            ('Microdermabrasion', 'Microdermabrasion'),
            ('Chemical Peels', 'Chemical Peels'),
            ('Facial Fillers', 'Facial Fillers'),
            ('Laser Facials', 'Laser Facials'),
            ('BOTOX', 'Botox'),
            ('Application', 'Make Up - Application'),
            ('Permanent', 'Make Up - Permanent Makeup'),
            ('Womens Cut', 'Womens Cut'),
            ('Conditioning Treatments', 'Conditioning Treatments'),
            ('Blowout', 'Blowout'),
            ('Updo', 'Updo'),
            ('Extensions', 'Extensions'),
            ('Straightening', 'Straightening'),
            ('Mens Cut', 'Mens Cut'),
            ('Brows/Face', 'Brows/Face'),
            ('Bikini/Brazilian', 'Bikini/Brazilian'),
            ('Body', 'Body'),
            ('Mens', 'Mens'),
            ('Laser', 'Laser'),
            ('Threading', 'Threading'),
            ('Sugaring', 'Sugaring'),
            ('Electrolysis', 'Electrolysis'),
            ('Pedicure', 'Pedicure'),
            ('Manicure', 'Manicure'),
            ('Mani/pedi', 'Mani/pedi'),
            ('Polish Change', 'Polish Change'),
            ('Gels', 'Gels'),
            ('Acrylics', 'Acrylics'),
            ('Yoga', 'Yoga'),
            ('Pilates', 'Pilates'),
            ('Cross Training Classes', 'Cross Training Classes'),
            ('Cycling Classes', 'Cycling Classes'),
            ('TRX', 'TRX'),
            ('Flexibility/Stretching Classes', 'Flexibility/Stretching Classes'),
            ('Outdoor Bootcamp', 'Outdoor Bootcamp'),
            ('Abs & Targeted Area Classes', 'Abs & Targeted Area Classes'),
            ('Personal Training', 'Personal Training'),
            ('Chiropractic', 'Chiropractic'),
            ('Acupuncture', 'Acupuncture'),
            ('Colonics', 'Colonics'),
            ('Weight Loss', 'Weight Loss'),
            ('Spray Tan', 'Tanning - Spray Tan'),
            ('Tanning Beds', 'Tanning - Tanning Beds'),
            ('Scrubs', 'Scrubs'),
            ('Wraps', 'Wraps'),
            ('Back Facials', 'Back Facials'),
            ('Cleaning', 'Dental - Cleaning'),
            ('Whitening', 'Dental - Whitening'),
            )
    category = models.CharField(max_length=50, choices=DECISION_TREE)

    class Meta:
        verbose_name_plural = "Category"

    def __unicode__(self):
        return self.category

class Procedure(models.Model):
    DECISION_TREE = (
            ('Therapeutic', 'Therapeutic'),
            ('Thai', 'Thai'),
            ('Hot Stone', 'Hot Stone'),
            ('Reflexology', 'Reflexology'),
            ('Facials', 'Facials'),
            ('Lash Extensions', 'Lash Extensions'),
            ('Lash Tinting', 'Lash Tinting'),
            ('Brow Tinting', 'Brow Tinting'),
            ('Microdermabrasion', 'Microdermabrasion'),
            ('Chemical Peels', 'Chemical Peels'),
            ('Facial Fillers', 'Facial Fillers'),
            ('Laser Facials', 'Laser Facials'),
            ('BOTOX', 'Botox'),
            ('Application', 'Make Up - Application'),
            ('Permanent', 'Make Up - Permanent Makeup'),
            ('Womens Cut', 'Womens Cut'),
            ('Conditioning Treatments', 'Conditioning Treatments'),
            ('Blowout', 'Blowout'),
            ('Updo', 'Updo'),
            ('Extensions', 'Extensions'),
            ('Straightening', 'Straightening'),
            ('Mens Cut', 'Mens Cut'),
            ('Brows/Face', 'Brows/Face'),
            ('Bikini/Brazilian', 'Bikini/Brazilian'),
            ('Body', 'Body'),
            ('Mens', 'Mens'),
            ('Laser', 'Laser'),
            ('Threading', 'Threading'),
            ('Sugaring', 'Sugaring'),
            ('Electrolysis', 'Electrolysis'),
            ('Pedicure', 'Pedicure'),
            ('Manicure', 'Manicure'),
            ('Mani/pedi', 'Mani/pedi'),
            ('Polish Change', 'Polish Change'),
            ('Gels', 'Gels'),
            ('Acrylics', 'Acrylics'),
            ('Yoga', 'Yoga'),
            ('Pilates', 'Pilates'),
            ('Cross Training Classes', 'Cross Training Classes'),
            ('Cycling Classes', 'Cycling Classes'),
            ('TRX', 'TRX'),
            ('Flexibility/Stretching Classes', 'Flexibility/Stretching Classes'),
            ('Outdoor Bootcamp', 'Outdoor Bootcamp'),
            ('Abs & Targeted Area Classes', 'Abs & Targeted Area Classes'),
            ('Personal Training', 'Personal Training'),
            ('Chiropractic', 'Chiropractic'),
            ('Acupuncture', 'Acupuncture'),
            ('Colonics', 'Colonics'),
            ('Weight Loss', 'Weight Loss'),
            ('Spray Tan', 'Tanning - Spray Tan'),
            ('Tanning Beds', 'Tanning - Tanning Beds'),
            ('Scrubs', 'Scrubs'),
            ('Wraps', 'Wraps'),
            ('Back Facials', 'Back Facials'),
            ('Cleaning', 'Dental - Cleaning'),
            ('Whitening', 'Dental - Whitening'),
            )

    category = models.CharField(max_length=50, choices=DECISION_TREE)
    spa = models.ForeignKey(Spa)
    procedure = models.CharField(max_length=100)
    price = models.IntegerField()
    discount = models.IntegerField()
    #category = models.ForeignKey(Category)

    def __unicode__(self):
        return self.procedure

class Availability(models.Model):

    STATUS =(
            (0,'Available'),
            (1,'Booked'),
            (2,'Completed'),
            (3,'No Show')
            )

    TIMESLOTS = (
            (37, '9:00 am'),
            (38, '9:15 am'),
            (39, '9:30 am'),
            (40, '9:45 am'),
            (41, '10:00 am'),
            (42, '10:15 am'),
            (43, '10:30 am'),
            (44, '10:45 am'),
            (45, '11:00 am'),
            (46, '11:15 am'),
            (47, '11:30 am'),
            (48, '11:45 am'),
            (49, '12:00 pm'),
            (50, '12:15 pm'),
            (51, '12:30 pm'),
            (52, '12:45 pm'),
            (53, '1:00 pm'),
            (54, '1:15 pm'),
            (55, '1:30 pm'),
            (56, '1:45 pm'),
            (57, '2:00 pm'),
            (58, '2:15 pm'),
            (59, '2:30 pm'),
            (60, '2:45 pm'),
            (61, '3:00 pm'),
            (62, '3:15 pm'),
            (63, '3:30 pm'),
            (64, '3:45 pm'),
            (65, '4:00 pm'),
            (66, '4:15 pm'),
            (67, '4:30 pm'),
            (68, '4:45 pm'),
            (69, '5:00 pm'),
            (70, '5:15 pm'),
            (71, '5:30 pm'),
            (72, '5:45 pm'),
            (73, '6:00 pm'),
            (74, '6:15 pm'),
            (75, '6:30 pm'),
            (76, '6:45 pm'),
            (77, '7:00 pm'),
            (78, '7:15 pm'),
            (79, '7:30 pm'),
            (80, '7:45 pm'),
            (81, '8:00 pm'),
            (82, '8:15 pm'),
            (83, '8:30 pm'),
            (84, '8:45 pm'),
            )

   
            
    procedure = models.ForeignKey(Procedure)
    appt_date = models.DateField("Appointment Date")
    spa = models.ForeignKey(Spa)
    timeslot = models.IntegerField(choices=TIMESLOTS)
    duration = models.IntegerField()
    status = models.IntegerField(choices=STATUS) 
    base_price = models.IntegerField()
    proc_name = models.ForeignKey(Procedure, related_name='Procedure')
    create_date = models.DateField()
    staff_id = models.IntegerField()
    customer_id = models.IntegerField(default=0, null=True)
   
    class Meta:
        verbose_name_plural = "Availability"

juvume/look/views.py
from random import choice, shuffle
from simplejson import dumps
from itertools import cycle
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect, HttpResponseRedirect
from django.contrib import auth
from look.models import Availability
#from look.models import Category
from look.models import Procedure
import datetime

def image_url(n):
    return '/static/image/login_%02i.jpg' % (n,)

def home(request):
    '''
    Login page with rotating background images.
    '''
    LOGIN_IMAGES = [
        dict(
            image_URL=image_url(1),
            top='37%',
            left='22%',
            color='#3998C2',
            ),
        dict(
            image_URL=image_url(2),
            top='19%',
            left='52%',
            color='#C7AA9C',
            ),
        dict(
            image_URL=image_url(3),
            top='38%',
            left='52%',
            color='#6A8CA9',
            ),
        dict(
            image_URL=image_url(4),
            top='40%', 
            left='52%',
            color='#E8711F',
            ),
        dict(
            image_URL=image_url(5),
            top='20%',
            left='48%',
            color='#C7452E',
            ),
        dict(
            image_URL=image_url(6),
            top='15%',
            left='45%',
            color='#7B4730',
            ),
        ]

    i = cycle(LOGIN_IMAGES).next

    if request.method != 'POST':
        return render_to_response(
            'booking.html',
            i(),
            context_instance=RequestContext(request),
            )

    username = request.POST['username']
    password = request.POST['password']
    user = auth.authenticate(username=username, password=password)
    if user and user.is_active:
        auth.login(request, user)
        return redirect("/look/#service")
    return redirect('/invalid_login')

def hooray(request):
    # login bypasses this and returns /look/#service
    return render_to_response(
            'book.html',
            context_instance=RequestContext(request),
            )



def inv(request):
    '''
    Inventory page.
    '''

    




    #if request.method == 'POST':
    #    results = get_results(
	#   proc=request.POST.get('proc'),
	#   from_date=request.POST.get('from_date'),
	#   to_date=request.POST.get('to_date'),
	#  )
   	# else:
    #   results = get_results(None, None, None)
    #shuffle(results)
    

    #new by DC

    print request.POST.get('proc')
    print request.POST.get('from_date')
    print request.POST.get('to_date')

    from_date = datetime.datetime.strptime(request.POST.get('from_date'),'%m/%d/%Y')
    to_date = datetime.datetime.strptime(request.POST.get('to_date'),'%m/%d/%Y')
    print from_date
    print to_date
    #print datetime.datetime.today()


    avail = Availability.objects.select_related().filter(procedure__category__iexact=request.POST.get('proc')).filter(appt_date=from_date)

    print avail.count()
    for each_avail in avail:
		print each_avail.base_price

    price =  avail.values_list('base_price').distinct().order_by('base_price')

    json_result = "["
    
    for each_price in price:
    	json_result += "{base_price:" + str(each_price[0]) + ",appts:["
    	avail = Availability.objects.filter(appt_date=datetime.datetime.today()).filter(base_price=each_price[0])
    	for each_avail in avail:
    		#print each_avail.base_price,each_avail.proc_name
    		json_result += "{spa_name:'" + each_avail.spa.name + "',timeslot:'" + str(each_avail.timeslot) + "',duration:'" + str(each_avail.duration)+ "'}"	
    	json_result += "]},"		
    json_result += "]"	
    
    x=dict()		
    x['proc'] = request.POST.get('proc')
    x['date'] = datetime.datetime.now()
    x['image_URL'] = '/static/image/inv.jpeg'
    # x['image_URL']=image_url(1)
  #  x['avail'] = avail
  #  x['price'] = price 
    x['json_result'] = json_result
    
    '''
    END DC
    '''
    print json_result
    print x['proc']
        
    return render_to_response(
        'inv.html',
        x,
        context_instance=RequestContext(request),
        )    
        
        
        

def book(request):
    '''
    booking page.
    '''
    results = FAKER_RESULTS
    if request.method == 'POST':
        FAKER_RESULTS['treatment'] = request.POST['name']
       # {'treatment': request.POST['name']}
                
        # treatment = request.POST['name']
    else:
        return HttpResponseRedirect('inv')
    return render_to_response(
        'book.html',
        results,
        context_instance=RequestContext(request),
        )

def book_info(request):
    '''
    capture client's information
    '''
    return render_to_response(
        'book_info_capture.html',
        context_instance=RequestContext(request),
        )


def book_confirm(request):
    '''
    confirm client's information
    '''
    return render_to_response(
        'book_info_confirm.html',
        context_instance=RequestContext(request),
        )


def book_congrats(request):
    '''
    book congratulations
    '''
    return render_to_response(
        'book_congrats.html',
        context_instance=RequestContext(request),
        )

juvume/look/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="language" content="en">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="author" content="Juvu.me">
	<meta name="publisher" content="Agora Health Networks, Inc.">
	<meta name="copyright" content="©2011 Agora Health Networks, Inc. All rights reserved worldwide.">
	<meta http-equiv="pragma" content="no-cache">
	<title>{% block title %}Beauty{% endblock %}</title>
{% block html_head %}{% endblock %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

juvume/look/templates/inv_old.html
{% extends "base.html" %}
{% block title %}Juvu{% endblock %}
{% block html_head %}
{# Template ================================================= #}
<script id="result_template" type="text/x-jquery-tmpl">
{% include "templates.inv.html" %}
</script>
{# ========================================================== #}
<script type="text/javascript" src="/static/js/booking.js"></script>
<script type="text/javascript" src="/static/js/inv.js"></script>
<link rel="stylesheet" type="text/css" href="/static/css/booking.css">
<script type="text/javascript">
		//color, size
		var first_color = "#E6E6E6",
		    second_color = "#808080",
		    third_color = "#3FA9F5",
		    hover_color = "#C6E6FC",
		    c_size = 30,
		    oc,
		    s_canvas;

		$(function(){
			
			var s_canvas = d3.select(".canvas").append("svg:svg");
			s_canvas
				.attr("width", 300)
				.attr("height", 800)
				.attr("class", "s_canvas");
			
			//where
			s_canvas.append("svg:circle")
				.attr("cx",150)
				.attr("cy",100)
				.attr("r",c_size)
				.attr("fill",first_color)
				.attr("class","c_where")
				.on("click",function(){
					/*depend on what user selects from previous page*/
					clickNeighbor();
					//or clickDistance();
				})
				.on('mouseover', function(){
					changeColor($(this));
				})
				.on('mouseout', function(){
					changeBack($(this));
				});
			
			//html
			$('.where').mouseover(function(){
				changeColor($('.c_where'));
			});
			
			$('.where').mouseout(function(){
				changeBack($('.c_where'));
			});
			
			$('.where').click(function(){
				/*depend on what user selects from previous page*/
				clickNeighbor();
				//or clickDistance();
			});
			
			//when
			s_canvas.append("svg:circle")
				.attr("cx",150)
				.attr("cy",200)
				.attr("r",c_size)
				.attr("fill",first_color)
				.attr("class","c_when")
				.on("click", clickDate)
				.on('mouseover', function(){
					changeColor($(this));
				})
				.on('mouseout', function(){
					changeBack($(this));
				});
			
			//html
			$('.when').mouseover(function(){
				changeColor($('.c_when'));
			});
			
			$('.when').mouseout(function(){
				changeBack($('.c_when'));
			});
			
			$('.when').click(clickDate);
			
			//options
			s_canvas.append("svg:circle")
				.attr("cx",150)
				.attr("cy",300)
				.attr("r",c_size)
				.attr("fill",first_color)
				.attr("class","c_op")
				.on("click", clickOption)
				.on('mouseover', function(){
					changeColor($(this));
				})
				.on('mouseout', function(){
					changeBack($(this));
				});
			
			//html
			$('.option').mouseover(function(){
				changeColor($('.c_op'));
			});
			
			$('.option').mouseout(function(){
				changeBack($('.c_op'));
			});

			$('.option').click(clickOption);

			//distance & neighboehood
			s_canvas.append("svg:circle")
				.attr("cx",105)
				.attr("cy",80)
				.attr("r",0)
				.attr("fill",first_color)
				.attr("class","c_dis")	
				.on("click",function(){
					$(this).attr('fill',first_color);
					clickDistance();
				})
				.on('mouseover', function(){
					changeColor($(this));
				})
				.on('mouseout', function(){
					changeBack($(this));
				});
			
			$('.distance').mouseover(function(){
				changeColor($('.c_dis'));
			});
			
			$('.distance').mouseout(function(){
				changeBack($('.c_dis'));
			});
			
			$('.distance').click(clickDistance);


			s_canvas.append("svg:circle")
				.attr("cx",200)
				.attr("cy",130)
				.attr("r",0)
				.attr("fill",second_color)
				.attr("class","c_nei")
				.on("click",function(){
					$(this).attr('fill',second_color);
					clickNeighbor();
				})
				.on('mouseover', function(){
					changeColor($(this));
				})
				.on('mouseout', function(){
					changeBack($(this));
				});
			
			$('.neighbor').mouseover(function(){
				changeColor($('.c_nei'));
			});
			
			$('.neighbor').mouseout(function(){
				changeBack($('.c_nei'));
			});
			
			$('.neighbor').click(clickNeighbor);
			
			//today & date --- only have one animation result
			s_canvas.append("svg:circle")
				.attr("cx",120)
				.attr("cy",240)
				.attr("r",0)
				.attr("fill",first_color)
				.attr("class","c_today")
				.on("click",function(){
					original();
				})
				.on('mouseover', function(){
					changeColor($(this));
				})
				.on('mouseout', function(){
					changeBack($(this));
				});
			
			$('.today').mouseover(function(){
				changeColor($('.c_today'));
			});
			
			$('.today').mouseout(function(){
				changeBack($('.c_today'));
			});
			
			$('.today').click(function(){
				original();
			});
			
			s_canvas.append("svg:circle")
				.attr("cx",200)
				.attr("cy",300)
				.attr("r",0)
				.attr("fill",second_color)
				.attr("class","c_date")
				.on("click",function(){
					$(this).attr('fill',second_color);
					clickDate();
				})
				.on('mouseover', function(){
					changeColor($(this));
				})
				.on('mouseout', function(){
					changeBack($(this));
				});
			
			$('.date').mouseover(function(){
				changeColor($('.c_date'));
			});
			
			$('.date').mouseout(function(){
				changeBack($('.c_date'));
			});
			
			$('.date').click(function(){
				clickDate();
			});
			
			$('.submit_btn').click(original)

    $(".b_btn").mouseover(function(){
	    $(this).parent()
	    .find(".service, .price, .discount")
	    .css({'background-color':'#C6E6FC'})
    });
    $(".b_btn").mouseout(function(){
	    $(this).parent()
	    .find(".service, .price, .discount")
	    .css({'background-color':'white'})
    });

    var results = {{ results|safe }};
    MODEL.set_results(_.map(results, function(data){ return new MerchantThing(data) }));

    ko.applyBindings(MODEL);

});
</script>
{% endblock %}
{% block body %}
	<div class="wrapper">
		<div class="top-nav">
			<div class="utility"><a href="#">( log out )</a></div>
			<div class="utility"><a href="#">{{ user }}</a></div>
			<div class="logo">
				<img src="../static/image/logo.png" />
			</div>
			<div class="tagline">
				<img src="../static/image/tagline.png" />
			</div>
		</div>
		
		<div id="nav_left">
			<div class="animation">
				<div class="canvas"></div>
				<div class="where">where</div>
				<div class="when">when</div>
				
				<div class="distance">Distance</div>
				<form method="" action="" class="dis_form">
					<input type="textarea" style="width:30px;height:10px;" /> miles from<br/>
					355 Bryant Street, San Francisco <a href="#">(edit)</a><br/>
					<input type="submit" value="confirm" class="submit_btn" style="margin-left:-7px;margin-top:0px;"/>
					<a href="#" class="submit_btn">test</a>
				</form>
				
				<div class="neighbor">Neighborhood</div>
				<form method="" action="" class="nei_form">
					<p>
						<input type="checkbox" />Richmond/Presidio<br />
						<input type="checkbox" />Marina/Cow Hollow<br />
						<input type="checkbox" />Pacific Heights<br />
						<input type="checkbox" />Russian Hill/Nob Hill<br />
						<input type="checkbox" />Ingleside/Excelsior<br />
						<input type="checkbox" />North Beach/Fisherman's Wharf<br />
						<input type="checkbox" />Union Sq/Civic Ctr/FiDi<br />
						<input type="checkbox" />SoMa/South Beach<br />
						<input type="checkbox" />Haight<br />
					</p>
					<p>
						<input type="checkbox" />Castro<br />
						<input type="checkbox" />Mission<br />
						<input type="checkbox" />Potrero Hill<br />
						<input type="checkbox" />Noe Valley<br />
						<input type="checkbox" />Bernal Heights<br />
						<input type="checkbox" />Twin Peaks<br />
						<input type="checkbox" />Sunset/Lake Merced<br />
						<input type="checkbox" />Western Addition<br />
					</p>
					<input type="submit" value="confirm" class="submit_btn" style="margin-left:15px;margin-top:-10px;"/>
					<a href="#" class="submit_btn">test</a>
				</form>
				
				
				<div class="today">Today</div>
				<div class="date">Date Range</div>
				<form method="" action="" class="date_form">
					From <input type="textarea" style="width:60px;"/> to <input type="textarea" style="width:60px;"/>
					<input type="submit" value="confirm" class="submit_btn" style="margin-left:5px;"/>
					<a href="#" class="submit_btn">test</a>
				</form>
				
				<div class="option">options</div>	
				<form method="" action="">
					<ul class="op_list">
						<li>Price from <input type="textarea" style="width:60px;height:10px;"/> to <input type="textarea" style="width:60px;height:10px;"/></li>
						<li>Discount <input type="textarea" style="width:60px;height:10px;"/> %</li>
						<li>Amenities
							<ul>
								<li>Lockers/Robes &nbsp;</li> 
								<li>Steam/Sauna &nbsp;</li>
								<li>Showers &nbsp;</li>
								<li>Pool &nbsp;</li>
							</ul>
							<div style="clear:both;">
						</li>
						<li>Credit Cards</li>
						<li>Public Trans</li>
						<li>Parking</li>
						<li>Me+ <input type="textarea" style="width:30px;height:10px;"/></li>
						<input type="submit" value="confirm" class="submit_btn" style="margin-top:5px;"/>
						<a href="#" class="submit_btn">test</a>
					</ul>
				</form>
				
				
				
			</div><!--end of animation-->
		</div><!--end of left nav-->
		
		<div id="nav_right">
{# container of information from database #}
<div data-bind="template: {name:'result_template', foreach:results}"></div>
		</div>{# end of right nav #}
		<div style="clear:both;"></div>
	</div>{# end of wrapper #}


<form id="submitter" action="{% url book %}" method="POST"  style="display:none;">
  {% csrf_token %}
  <input name="name" id="id_name" type="text"/>
  <input name="price" id="id_price" type="text"/>
  <input name="discount" id="id_discount" type="text"/>
</form>

{% endblock %}

juvume/look/templates/templates.inv.html
<div class="m_row">
	<img class="m_img" width="240" height="180" data-bind="attr:{src:logo_image_URL}">
	<div class="m_info">
		<div class="m_name" data-bind="text:name">Merchant Name</div>
		<ul class="m_itemsName">
			<li class="service">service</li>
			<li class="price">high price</li>
      <li class="discount">low price</li>
		</ul>
<!-- ko foreach:{data:results, afterRender:wire_up_buttons} -->
        <ul class="m_items">
	        <li class="service" data-bind="text:name">Theraputic Massage</li>
	        <li class="price" data-bind="text:price">125</li>
	        <li class="discount"> </li>
	        <div class="b_btn" data-bind="click:book">book</div>
	        <div class="b_btn" data-bind="click:bid">bid</div>
        </ul>
<!-- /ko -->
		<div class="more_btn">more</div>	
	</div>
</div>